In [2]:
import numpy as np

hello = 'Hello, world.'
print(hello)

Hello, world.


In [3]:
# one-dimensional array
arr1 = np.array([1, 2, 3])
print (arr1)

[1 2 3]


In [12]:
# two-dimensional array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [18]:
# specify the number of dimensions
arr3 = np.array([1, 2, 3, 4, 5, 6], ndmin=3)
print(arr3)

# specify the data type
arr_float = np.array(arr3, dtype=float)
print(arr_float)

[[[1 2 3 4 5 6]]]
[[[1. 2. 3. 4. 5. 6.]]]


In [20]:
# activity
arr_bool = np.array([0,1,0,1], dtype=bool)
print(arr_bool)

[False  True False  True]


In [21]:
# get the array dimensions
print(arr3)
print(arr3.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [22]:
#resize an array using the .shape attribute
arr4 = np.array(arr2)
print(arr4)
print(arr4.shape, '\n')

arr4.shape = (4,1)
print(arr4)
print(arr4.shape)

[[1 2]
 [3 4]]
(2, 2) 

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [27]:
# reshape activity
arr5 = arr2.reshape(4,1)
print(arr5)

[[1]
 [2]
 [3]
 [4]]


In [28]:
# np.arange test
nump1 = np.arange(3)
print(nump1)

[0 1 2]


In [29]:
nump2 = np.arange(5,10)
print(nump2)

[5 6 7 8 9]


In [30]:
# np.linspace test
nump3 = np.linspace(0,10, num=5)
print(nump3)

[ 0.   2.5  5.   7.5 10. ]


In [36]:
nump4 = np.linspace(0,100, num=20, retstep=True)
print(nump4)

(array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ]), 5.2631578947368425)


In [38]:
# np.asarray test
a = [1, 2, 3]
nump5 = np.asarray(a)
print(nump5)

[1 2 3]


In [ ]:
#Activities
x = np.arange(1,20)
print(x)

y = np.linspace(1,20)
print(y)

 y has a longer length than x because of the difference in step size between the two, 
 with no step value given it will default to produce 50 numbers to get to stop value

In [40]:
xnum = [0, 10, 20, 30]
xnum_arr = np.asarray(xnum)
print(xnum_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
[ 0 10 20 30]


In [43]:
# slices
# the 0 value will be 5
d = np.arange(5,30, 2)
print(d)
print(d[:5])
print(d[2:5])
print(d[7:])
print(d[::-1])
# the -1 step value reverses the list

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]
[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [45]:
#combining arrays
m = np.array([9, 18, 27, 36])
n = np.array([10, 20, 30, 40])
o = np.array([7, 14, 21, 28])

print(np.concatenate([m,n]))
print(np.concatenate([m,n,o]))

print(np.vstack([m,n,o]))
print(np.hstack([m,n,o]))

[ 9 18 27 36 10 20 30 40]
[ 9 18 27 36 10 20 30 40  7 14 21 28]
[[ 9 18 27 36]
 [10 20 30 40]
 [ 7 14 21 28]]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [46]:
#mathmatetical operations
r = np.arange(8)
print("r =", r)
print("r + 10 =", r + 10)
print("r / 2 =", r / 2)

r = [0 1 2 3 4 5 6 7]
r + 10 = [10 11 12 13 14 15 16 17]
r / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [50]:
#more mathematical operations
s = np.arange(100)
def div_by_2(array):
    v = np.empty(len(array))
    for i in range(len(array)):
        v[i] = i / 2
    return v
r2 = div_by_2(r)
print(r2)

%timeit s2_numpy = s / 2
print(len(s2_numpy))

%timeit s2_loop = div_by_2(s)
print(len(s2_loop))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5]
1.11 µs ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
100
8.62 µs ± 34.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100


In [52]:
#summary statistics

t = np.random.random(1000)
t_range = (t.min(), t.max())
print(np.sum(t))
print(t_range)

518.2345047491547
(0.001037745918676003, 0.9986697794947226)


In [54]:
u = np.random.random((3,4))
print(u)
print(u.sum(axis=0)) #sums the numbers in columns
print(u.sum(axis=1)) #sums the numbers in rows

[[0.56031962 0.69338188 0.3906321  0.67948986]
 [0.86035625 0.36027877 0.42489407 0.82421246]
 [0.33232315 0.25231443 0.71584139 0.3217388 ]]
[1.75299902 1.30597508 1.53136756 1.82544112]
[2.32382346 2.46974155 1.62221777]


In [68]:
#random activity
rand = np.random.randint(1,10, size=100)
rand1 = np.mean(rand)
rand2 = np.median(rand)
rand3 = np.std(rand)
rand4 = np.var(rand)
print(rand)
print("Mean =", rand1)
print("Median =", rand2)
print("Standard Deviation =", rand3)
print("Variance =", rand4)

[7 8 6 6 5 3 5 6 7 1 4 5 6 2 9 8 6 4 2 6 7 6 5 9 1 7 5 2 1 9 3 4 7 4 2 7 7
 8 6 5 8 4 3 6 3 5 1 4 5 5 3 3 2 8 1 5 1 8 9 8 4 9 1 4 9 3 6 5 7 3 4 7 4 8
 8 1 2 5 7 2 9 2 3 1 2 5 1 4 1 6 8 4 1 9 9 9 1 7 7 6]
Mean = 4.97
Median = 5.0
Standard Deviation = 2.543442548987494
Variance = 6.4691
